package com.bao.lc.client;

public enum ResultCode
{
	RC_OK,
	RC_UNKOWN,
	RC_LOGIN_FAILED,
	RC_HTTP_ERROR,
	RC_REG_LIST_EMPTY,
	RC_DOCTOR_NOT_EXIST,
	RC_DOCTOR_DETAIL_LIST_EMPTY,
	RC_DOCTOR_REG_LIST_FULL,
	RC_REG_MESSAGE_SUCCESS,
	RC_REG_MESSAGE_FAIL,
	RC_ALREADY_REGISTERED,
	RC_NO_MATCHED_RECORD,
	RC_XXX;
	
}
