@echo off

set PATH=%VS6_HOME%\Common\msdev98\BIN;%VS6_HOME%\VC98\BIN;%VS6_HOME%\Common\TOOLS\WINNT;%VS6_HOME%\Common\TOOLS;%PATH%
set INCLUDE=%VS6_HOME%\VC98\ATL\INCLUDE;%VS6_HOME%\VC98\INCLUDE;%VS6_HOME%\VC98\MFC\INCLUDE;%INCLUDE%
set LIB=%VS6_HOME%\VC98\LIB;%VS6_HOME%\VC98\MFC\LIB;%LIB%

